/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright 2019 NXP
 */

#ifndef __DT_BINDINGS_CLOCK1_IMX8MP_H
#define __DT_BINDINGS_CLOCK1_IMX8MP_H

/* HDMIMIX CLK */
#define IMX8MP_CLK_HDMIMIX_GLOBAL_APB_CLK		0
#define IMX8MP_CLK_HDMIMIX_GLOBAL_B_CLK			1
#define IMX8MP_CLK_HDMIMIX_GLOBAL_REF266M_CLK	2
#define IMX8MP_CLK_HDMIMIX_GLOBAL_XTAL24M_CLK	3
#define IMX8MP_CLK_HDMIMIX_GLOBAL_XTAL32K_CLK	4
#define IMX8MP_CLK_HDMIMIX_GLOBAL_TX_PIX_CLK	5
#define IMX8MP_CLK_HDMIMIX_IRQS_STEER_CLK		6
#define IMX8MP_CLK_HDMIMIX_NOC_HDMI_CLK			7
#define IMX8MP_CLK_HDMIMIX_NOC_HDCP_CLK			8
#define IMX8MP_CLK_HDMIMIX_LCDIF_APB_CLK		9
#define IMX8MP_CLK_HDMIMIX_LCDIF_B_CLK			10
#define IMX8MP_CLK_HDMIMIX_LCDIF_PDI_CLK		11
#define IMX8MP_CLK_HDMIMIX_LCDIF_PIX_CLK		12
#define IMX8MP_CLK_HDMIMIX_LCDIF_SPU_CLK		13
#define IMX8MP_CLK_HDMIMIX_FDCC_REF_CLK			14
#define IMX8MP_CLK_HDMIMIX_HRV_MWR_APB_CLK		15
#define IMX8MP_CLK_HDMIMIX_HRV_MWR_B_CLK		16
#define IMX8MP_CLK_HDMIMIX_HRV_MWR_CEA_CLK		17
#define IMX8MP_CLK_HDMIMIX_VSFD_CEA_CLK			18
#define IMX8MP_CLK_HDMIMIX_TX_HPI_CLK			19
#define IMX8MP_CLK_HDMIMIX_TX_APB_CLK			20
#define IMX8MP_CLK_HDMIMIX_TX_CEC_CLK			21
#define IMX8MP_CLK_HDMIMIX_TX_ESM_CLK			22
#define IMX8MP_CLK_HDMIMIX_TX_GPA_CLK			23
#define IMX8MP_CLK_HDMIMIX_TX_PIXEL_CLK			24
#define IMX8MP_CLK_HDMIMIX_TX_SFR_CLK			25
#define IMX8MP_CLK_HDMIMIX_TX_SKP_CLK			26
#define IMX8MP_CLK_HDMIMIX_TX_PREP_CLK			27
#define IMX8MP_CLK_HDMIMIX_TX_PHY_APB_CLK		28
#define IMX8MP_CLK_HDMIMIX_TX_PHY_INT_CLK		29
#define IMX8MP_CLK_HDMIMIX_TX_SEC_MEM_CLK		30
#define IMX8MP_CLK_HDMIMIX_TX_TRNG_SKP_CLK		31
#define IMX8MP_CLK_HDMIMIX_TX_VID_LINK_PIX_CLK	32
#define IMX8MP_CLK_HDMIMIX_TX_TRNG_APB_CLK		33
#define IMX8MP_CLK_HDMIMIX_HTXPHY_CLK_SEL		34
#define IMX8MP_CLK_HDMIMIX_LCDIF_CLK_SEL		35
#define IMX8MP_CLK_HDMIMIX_TX_PIPE_CLK_SEL		36

#define IMX8MP_CLK_HDMIMIX_END					37

#endif
