/*
 * SPDX-License-Identifier:	GPL-2.0+
 *
 * AUTO-GENERATED by gen_ddr_tables.py -- DO NOT EDIT BY HAND.
 */


#ifndef __DDR_CFG_SIZES_H__
#define __DDR_CFG_SIZES_H__

#define DRAM_DDRC_CFG_MAX	106
#define DRAM_DDRPHY_CFG_MAX	200
#define DRAM_FSP0_CFG_MAX	35
#define DRAM_FSP1_CFG_MAX	36
#define DRAM_FSP2_CFG_MAX	36
#define DRAM_FSP0_2D_CFG_MAX	36
#define DRAM_DDRPHY_PIE_MAX	592

#endif /* __DDR_CFG_SIZES_H__ */
