/*
 * SPDX-License-Identifier:	GPL-2.0+
 *
 * AUTO-GENERATED by gen_ddr_tables.py -- DO NOT EDIT BY HAND.
 */


#ifndef __DDR_CFG_BASES_H__
#define __DDR_CFG_BASES_H__

#include <asm/arch/imx8m_ddr.h>

#define BASE_DDRC_CFG_NUM	103
extern const struct dram_cfg_param base_ddrc_cfg[BASE_DDRC_CFG_NUM];

#define BASE_DDRPHY_CFG_NUM	200
extern const struct dram_cfg_param base_ddrphy_cfg[BASE_DDRPHY_CFG_NUM];

#define BASE_FSP0_CFG_NUM	35
extern const struct dram_cfg_param base_fsp0_cfg[BASE_FSP0_CFG_NUM];

#define BASE_FSP1_CFG_NUM	36
extern const struct dram_cfg_param base_fsp1_cfg[BASE_FSP1_CFG_NUM];

#define BASE_FSP2_CFG_NUM	36
extern const struct dram_cfg_param base_fsp2_cfg[BASE_FSP2_CFG_NUM];

#define BASE_FSP0_2D_CFG_NUM	36
extern const struct dram_cfg_param base_fsp0_2d_cfg[BASE_FSP0_2D_CFG_NUM];

#define BASE_DDRPHY_PIE_NUM	592
extern const struct dram_cfg_param base_ddrphy_pie[BASE_DDRPHY_PIE_NUM];

#endif /* __DDR_CFG_BASES_H__ */
