#!/usr/bin/env python3
"""Generate compact base+patch DDR timing tables from the original
lpddr4_timing_*.c NXP-tool-generated sources.

Each `struct dram_timing_info` sub-table (ddrc_cfg, ddrphy_cfg, the four
fsp*_cfg tables, ddrphy_pie) is >60% identical across all profiles in this
board's SoM. This script picks one shared "base" array per sub-table role
(minimizing total base+patch bytes across all profiles) and rewrites every
profile as a short patch list (set/insert/delete) against that base.

Before writing anything, every (role, profile) reconstruction is verified
byte-for-byte against the original parsed array, using a Python
transliteration of the runtime C merge algorithm in ddr_patch.c. If this
script and ddr_patch.c's dram_cfg_apply_patches() ever diverge, keep the
two in sync by hand -- this is the correctness contract the whole scheme
relies on.

Re-run this after regenerating any lpddr4_timing_*.c source from Compulab's/
NXP's DDR tuning tool (e.g. to add a new DRAM chip).

Usage: python3 gen_ddr_tables.py [--check]
    --check   parse + diff + self-verify only, do not write any files
"""
import re
import sys
import difflib
from pathlib import Path

DDR_DIR = Path(__file__).resolve().parent
SRC_FILES = ["lpddr4_timing_01050008.c", "lpddr4_timing_01061010.c",
             "lpddr4_timing_05000010.c", "lpddr4_timing_1b000008.c",
             "lpddr4_timing_ff000110.c", "lpddr4_timing_ff020008.c",
             "lpddr4_timing_ff070010.c", "lpddr4_timing_ff070018.c",
             "lpddr4_timing_ff070110.c"]

ROLES = ["ddrc_cfg", "ddrphy_cfg", "fsp0_cfg", "fsp1_cfg", "fsp2_cfg",
         "fsp0_2d_cfg", "ddrphy_pie"]

ROLE_BASE = {
    "ddrc_cfg":    ("base_ddrc_cfg", "BASE_DDRC_CFG_NUM"),
    "ddrphy_cfg":  ("base_ddrphy_cfg", "BASE_DDRPHY_CFG_NUM"),
    "fsp0_cfg":    ("base_fsp0_cfg", "BASE_FSP0_CFG_NUM"),
    "fsp1_cfg":    ("base_fsp1_cfg", "BASE_FSP1_CFG_NUM"),
    "fsp2_cfg":    ("base_fsp2_cfg", "BASE_FSP2_CFG_NUM"),
    "fsp0_2d_cfg": ("base_fsp0_2d_cfg", "BASE_FSP0_2D_CFG_NUM"),
    "ddrphy_pie":  ("base_ddrphy_pie", "BASE_DDRPHY_PIE_NUM"),
}

BANNER_H = """/*
 * SPDX-License-Identifier:\tGPL-2.0+
 *
 * AUTO-GENERATED by gen_ddr_tables.py -- DO NOT EDIT BY HAND.
 */
"""

ARRAY_RE = re.compile(
    r'(?:static\s+)?(?:const\s+)?struct\s+dram_cfg_param\s+(\w+)\s*\[\]\s*=\s*\{(.*?)\n\};',
    re.S)
ENTRY_RE = re.compile(r'\{\s*(0[xX][0-9a-fA-F]+)\s*,\s*(0[xX][0-9a-fA-F]+)\s*,?\s*\}')

FSP_MSG_RE = re.compile(
    r'(?:static\s+)?(?:const\s+)?struct\s+dram_fsp_msg\s+(\w+)\s*\[\]\s*=\s*\{(.*?)\n\};',
    re.S)
FSP_ENTRY_RE = re.compile(
    r'\.drate\s*=\s*(\d+)\s*,\s*\.fw_type\s*=\s*(\w+)\s*,\s*\.fsp_cfg\s*=\s*(\w+)\s*,', re.S)

TIMING_RE = re.compile(r'struct\s+dram_timing_info\s+(\w+)\s*=\s*\{(.*?)\n\};', re.S)
FSP_TABLE_RE = re.compile(r'\.fsp_table\s*=\s*\{([^}]*)\}')


def field(name, body, pname):
    m = re.search(rf'\.{re.escape(name)}\s*=\s*(\w+)\s*,', body)
    if not m:
        raise ValueError(f"{pname}: missing field .{name}")
    return m.group(1)


def parse_file(path):
    text = path.read_text()

    arrays = {}
    for m in ARRAY_RE.finditer(text):
        name, body = m.group(1), m.group(2)
        entries = [(int(r, 16), int(v, 16)) for r, v in ENTRY_RE.findall(body)]
        if not entries:
            raise ValueError(f"{path.name}: array {name} parsed with 0 entries")
        arrays[name] = entries

    fsp_msgs = {}
    for m in FSP_MSG_RE.finditer(text):
        name, body = m.group(1), m.group(2)
        entries = FSP_ENTRY_RE.findall(body)
        fsp_msgs[name] = entries

    profiles = {}
    for m in TIMING_RE.finditer(text):
        pname, body = m.group(1), m.group(2)

        fsp_table_m = FSP_TABLE_RE.search(body)
        if not fsp_table_m:
            raise ValueError(f"{pname}: missing .fsp_table")
        fsp_table = [int(x.strip(), 0) for x in fsp_table_m.group(1).split(',') if x.strip()]
        if len(fsp_table) > 4:
            raise ValueError(f"{pname}: fsp_table has more than 4 entries")
        fsp_table += [0] * (4 - len(fsp_table))

        fsp_msg_name = field("fsp_msg", body, pname)
        fsp_entries = fsp_msgs[fsp_msg_name]
        if len(fsp_entries) != 4:
            raise ValueError(f"{pname}: expected 4 fsp_msg entries, got {len(fsp_entries)}")

        profiles[pname] = {
            "ddrc_cfg": arrays[field("ddrc_cfg", body, pname)],
            "ddrphy_cfg": arrays[field("ddrphy_cfg", body, pname)],
            "fsp0_cfg": arrays[fsp_entries[0][2]],
            "fsp1_cfg": arrays[fsp_entries[1][2]],
            "fsp2_cfg": arrays[fsp_entries[2][2]],
            "fsp0_2d_cfg": arrays[fsp_entries[3][2]],
            "ddrphy_pie": arrays[field("ddrphy_pie", body, pname)],
            "fsp_table": fsp_table,
        }
    if not profiles:
        raise ValueError(f"{path.name}: no dram_timing_info profiles found")
    return profiles


def diff_patches(base, target):
    """Turn a base->target sequence diff into (pos, op, reg, val) patches,
    pos always anchored to a BASE index, in ascending emission order."""
    sm = difflib.SequenceMatcher(None, base, target, autojunk=False)
    patches = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        if tag == "replace":
            rlen, tlen = i2 - i1, j2 - j1
            common = min(rlen, tlen)
            for k in range(common):
                reg, val = target[j1 + k]
                patches.append((i1 + k, "SET", reg, val))
            if tlen > rlen:
                for k in range(common, tlen):
                    reg, val = target[j1 + k]
                    patches.append((i2, "INSERT", reg, val))
            elif rlen > tlen:
                for pos in range(i1 + common, i2):
                    patches.append((pos, "DELETE", 0, 0))
        elif tag == "insert":
            for k in range(j1, j2):
                reg, val = target[k]
                patches.append((i1, "INSERT", reg, val))
        elif tag == "delete":
            for pos in range(i1, i2):
                patches.append((pos, "DELETE", 0, 0))
        else:
            raise ValueError(f"unexpected opcode {tag}")
    return patches


def apply_patches(base, patches):
    """Python transliteration of dram_cfg_apply_patches() in ddr_patch.c --
    must be kept in lockstep with that function."""
    out = []
    bi = pi = 0
    n_base, n_patch = len(base), len(patches)
    while bi < n_base or pi < n_patch:
        while pi < n_patch and patches[pi][0] <= bi:
            pos, op, reg, val = patches[pi]
            if op != "DELETE":
                out.append((reg, val))
            if op != "INSERT":
                bi += 1
            pi += 1
        if bi < n_base:
            out.append(base[bi])
            bi += 1
    return out


def patch_bytes(patches):
    return len(patches) * 12  # struct dram_cfg_patch, packed to 12 bytes


def pick_base(role, profiles):
    """Try every distinct array used by any profile for this role as the
    shared base; return the one minimizing base+patch bytes across all
    profiles, along with the per-profile patch lists against it."""
    candidates = {}
    for p in profiles.values():
        candidates.setdefault(tuple(p[role]), None)

    best = None
    for content in candidates:
        total = len(content) * 8
        per_profile = {}
        for pname, p in profiles.items():
            patches = diff_patches(list(content), p[role])
            per_profile[pname] = patches
            total += patch_bytes(patches)
        if best is None or total < best[0]:
            best = (total, list(content), per_profile)
    return best


def hexfmt(n):
    return f"0x{n:x}"


def emit_patch_array(name, patches):
    lines = [f"static const struct dram_cfg_patch {name}[] = {{"]
    for pos, op, reg, val in patches:
        if op == "DELETE":
            lines.append(f"\t{{ .pos = {pos}, .op = DRAM_PATCH_DELETE }},")
        else:
            opname = "DRAM_PATCH_SET" if op == "SET" else "DRAM_PATCH_INSERT"
            lines.append(f"\t{{ .pos = {pos}, .op = {opname}, "
                          f".reg = {hexfmt(reg)}, .val = {hexfmt(val)} }},")
    lines.append("};")
    return "\n".join(lines)


def profile_desc_name(pname):
    assert pname.startswith("ucm_dram_timing_")
    return "ucm_dram_profile_" + pname[len("ucm_dram_timing_"):]


def emit_profile_file(profile_names, role_result, profiles):
    out = [BANNER_H, "",
           "#include <linux/kernel.h>",
           "#include <asm/arch/imx8m_ddr.h>",
           '#include "ddr_patch.h"',
           '#include "ddr_cfg_bases.h"',
           ""]
    for pname in profile_names:
        suffix = pname[len("ucm_dram_timing_"):]
        role_field = {}
        for role in ROLES:
            base_name, base_num = ROLE_BASE[role]
            patches = role_result[role][2][pname]
            if patches:
                arr_name = f"{role}_patch_{suffix}"
                out.append(emit_patch_array(arr_name, patches))
                out.append("")
                role_field[role] = (f"{{ {base_name}, {base_num}, "
                                     f"{arr_name}, ARRAY_SIZE({arr_name}) }}")
            else:
                role_field[role] = f"{{ {base_name}, {base_num}, NULL, 0 }}"

        fsp_table = ", ".join(str(x) for x in profiles[pname]["fsp_table"])
        out.append(f"const struct dram_profile_desc {profile_desc_name(pname)} = {{")
        for role in ROLES:
            out.append(f"\t.{role} = {role_field[role]},")
        out.append(f"\t.fsp_table = {{ {fsp_table} }},")
        out.append("};")
        out.append("")
    return "\n".join(out)


def emit_bases_h(role_result):
    lines = [BANNER_H, "", "#ifndef __DDR_CFG_BASES_H__", "#define __DDR_CFG_BASES_H__", "",
             "#include <asm/arch/imx8m_ddr.h>", ""]
    for role in ROLES:
        base_name, base_num = ROLE_BASE[role]
        n = len(role_result[role][1])
        lines.append(f"#define {base_num}\t{n}")
        lines.append(f"extern const struct dram_cfg_param {base_name}[{base_num}];")
        lines.append("")
    lines.append("#endif /* __DDR_CFG_BASES_H__ */")
    return "\n".join(lines)


def emit_bases_c(role_result):
    lines = [BANNER_H, "", '#include "ddr_cfg_bases.h"', ""]
    for role in ROLES:
        base_name, base_num = ROLE_BASE[role]
        content = role_result[role][1]
        lines.append(f"const struct dram_cfg_param {base_name}[{base_num}] = {{")
        for reg, val in content:
            lines.append(f"\t{{{hexfmt(reg)},{hexfmt(val)}}},")
        lines.append("};")
        lines.append("")
    return "\n".join(lines)


def emit_sizes_h(profiles):
    max_len = {role: max(len(p[role]) for p in profiles.values()) for role in ROLES}
    name_map = {
        "ddrc_cfg": "DRAM_DDRC_CFG_MAX", "ddrphy_cfg": "DRAM_DDRPHY_CFG_MAX",
        "fsp0_cfg": "DRAM_FSP0_CFG_MAX", "fsp1_cfg": "DRAM_FSP1_CFG_MAX",
        "fsp2_cfg": "DRAM_FSP2_CFG_MAX", "fsp0_2d_cfg": "DRAM_FSP0_2D_CFG_MAX",
        "ddrphy_pie": "DRAM_DDRPHY_PIE_MAX",
    }
    lines = [BANNER_H, "", "#ifndef __DDR_CFG_SIZES_H__", "#define __DDR_CFG_SIZES_H__", ""]
    for role in ROLES:
        lines.append(f"#define {name_map[role]}\t{max_len[role]}")
    lines.append("")
    lines.append("#endif /* __DDR_CFG_SIZES_H__ */")
    return "\n".join(lines)


def main():
    check_only = "--check" in sys.argv

    profiles = {}
    profiles_by_file = {}
    for fname in SRC_FILES:
        path = DDR_DIR / fname
        file_profiles = parse_file(path)
        profiles_by_file[fname] = list(file_profiles.keys())
        profiles.update(file_profiles)

    print(f"Parsed {len(profiles)} profiles from {len(SRC_FILES)} files: "
          f"{', '.join(profiles)}")

    role_result = {}
    for role in ROLES:
        role_result[role] = pick_base(role, profiles)

    # Mandatory self-verification: reconstruct every (role, profile) pair
    # from base+patches and compare element-by-element against the
    # original parsed array. Abort on first mismatch -- nothing is written
    # unless every pair round-trips exactly.
    failures = 0
    for role in ROLES:
        _, base, per_profile = role_result[role]
        for pname, p in profiles.items():
            patches = per_profile[pname]
            rebuilt = apply_patches(base, patches)
            original = p[role]
            if rebuilt != original:
                failures += 1
                print(f"MISMATCH role={role} profile={pname}: "
                      f"rebuilt {len(rebuilt)} entries, original {len(original)} entries",
                      file=sys.stderr)
                for idx, (a, b) in enumerate(zip(rebuilt, original)):
                    if a != b:
                        print(f"  first differing index {idx}: rebuilt={a!r} original={b!r}",
                              file=sys.stderr)
                        break
    if failures:
        print(f"\n{failures} role/profile reconstructions FAILED self-check; "
              f"aborting, no files written.", file=sys.stderr)
        sys.exit(1)

    print("\nSelf-check passed: every role/profile reconstructs exactly.\n")

    # Summary: original bytes vs. chosen-base patch bytes, per role.
    print(f"{'role':<14}{'base bytes':>12}{'orig total':>14}{'patch total':>14}{'new total':>12}")
    grand_orig = grand_new = 0
    for role in ROLES:
        total, base, per_profile = role_result[role]
        base_bytes = len(base) * 8
        orig_total = sum(len(p[role]) * 8 for p in profiles.values())
        patch_total = sum(patch_bytes(per_profile[pname]) for pname in profiles)
        new_total = base_bytes + patch_total
        grand_orig += orig_total
        grand_new += new_total
        print(f"{role:<14}{base_bytes:>12}{orig_total:>14}{patch_total:>14}{new_total:>12}")
    print(f"{'TOTAL':<14}{'':>12}{grand_orig:>14}{'':>14}{grand_new:>12}")
    print(f"\nEstimated .rodata reduction: {grand_orig - grand_new} bytes "
          f"({100*(grand_orig-grand_new)/grand_orig:.0f}%)")

    if check_only:
        print("\n--check: not writing any files.")
        return

    (DDR_DIR / "ddr_cfg_bases.h").write_text(emit_bases_h(role_result) + "\n")
    (DDR_DIR / "ddr_cfg_bases.c").write_text(emit_bases_c(role_result) + "\n")
    (DDR_DIR / "ddr_cfg_sizes.h").write_text(emit_sizes_h(profiles) + "\n")

    for fname in SRC_FILES:
        content = emit_profile_file(profiles_by_file[fname], role_result, profiles)
        (DDR_DIR / fname).write_text(content + "\n")

    print("\nWrote ddr_cfg_bases.h, ddr_cfg_bases.c, ddr_cfg_sizes.h, and "
          f"rewrote {', '.join(SRC_FILES)}.")


if __name__ == "__main__":
    main()
