/*
 * SPDX-License-Identifier:	GPL-2.0+
 *
 * AUTO-GENERATED by gen_ddr_tables.py -- DO NOT EDIT BY HAND.
 */


#include <linux/kernel.h>
#include <asm/arch/imx8m_ddr.h>
#include "ddr_patch.h"
#include "ddr_cfg_bases.h"

const struct dram_profile_desc ucm_dram_profile_01061010 = {
	.ddrc_cfg = { base_ddrc_cfg, BASE_DDRC_CFG_NUM, NULL, 0 },
	.ddrphy_cfg = { base_ddrphy_cfg, BASE_DDRPHY_CFG_NUM, NULL, 0 },
	.fsp0_cfg = { base_fsp0_cfg, BASE_FSP0_CFG_NUM, NULL, 0 },
	.fsp1_cfg = { base_fsp1_cfg, BASE_FSP1_CFG_NUM, NULL, 0 },
	.fsp2_cfg = { base_fsp2_cfg, BASE_FSP2_CFG_NUM, NULL, 0 },
	.fsp0_2d_cfg = { base_fsp0_2d_cfg, BASE_FSP0_2D_CFG_NUM, NULL, 0 },
	.ddrphy_pie = { base_ddrphy_pie, BASE_DDRPHY_PIE_NUM, NULL, 0 },
	.fsp_table = { 3000, 400, 100, 0 },
};

