/*
 * SPDX-License-Identifier:	GPL-2.0+
 *
 * AUTO-GENERATED by gen_ddr_tables.py -- DO NOT EDIT BY HAND.
 */


#include <linux/kernel.h>
#include <asm/arch/imx8m_ddr.h>
#include "ddr_patch.h"
#include "ddr_cfg_bases.h"

static const struct dram_cfg_patch ddrc_cfg_patch_ff020008[] = {
	{ .pos = 2, .op = DRAM_PATCH_SET, .reg = 0x3d400000, .val = 0xa3080020 },
	{ .pos = 37, .op = DRAM_PATCH_SET, .reg = 0x3d400200, .val = 0x16 },
	{ .pos = 42, .op = DRAM_PATCH_SET, .reg = 0x3d400218, .val = 0xf070707 },
};

static const struct dram_cfg_patch fsp0_cfg_patch_ff020008[] = {
	{ .pos = 9, .op = DRAM_PATCH_SET, .reg = 0x54012, .val = 0x310 },
	{ .pos = 21, .op = DRAM_PATCH_SET, .reg = 0x5402c, .val = 0x3 },
};

static const struct dram_cfg_patch fsp1_cfg_patch_ff020008[] = {
	{ .pos = 10, .op = DRAM_PATCH_SET, .reg = 0x54012, .val = 0x310 },
	{ .pos = 22, .op = DRAM_PATCH_SET, .reg = 0x5402c, .val = 0x3 },
};

static const struct dram_cfg_patch fsp2_cfg_patch_ff020008[] = {
	{ .pos = 10, .op = DRAM_PATCH_SET, .reg = 0x54012, .val = 0x310 },
	{ .pos = 22, .op = DRAM_PATCH_SET, .reg = 0x5402c, .val = 0x3 },
};

static const struct dram_cfg_patch fsp0_2d_cfg_patch_ff020008[] = {
	{ .pos = 10, .op = DRAM_PATCH_SET, .reg = 0x54012, .val = 0x310 },
	{ .pos = 22, .op = DRAM_PATCH_SET, .reg = 0x5402c, .val = 0x3 },
};

const struct dram_profile_desc ucm_dram_profile_ff020008 = {
	.ddrc_cfg = { base_ddrc_cfg, BASE_DDRC_CFG_NUM, ddrc_cfg_patch_ff020008, ARRAY_SIZE(ddrc_cfg_patch_ff020008) },
	.ddrphy_cfg = { base_ddrphy_cfg, BASE_DDRPHY_CFG_NUM, NULL, 0 },
	.fsp0_cfg = { base_fsp0_cfg, BASE_FSP0_CFG_NUM, fsp0_cfg_patch_ff020008, ARRAY_SIZE(fsp0_cfg_patch_ff020008) },
	.fsp1_cfg = { base_fsp1_cfg, BASE_FSP1_CFG_NUM, fsp1_cfg_patch_ff020008, ARRAY_SIZE(fsp1_cfg_patch_ff020008) },
	.fsp2_cfg = { base_fsp2_cfg, BASE_FSP2_CFG_NUM, fsp2_cfg_patch_ff020008, ARRAY_SIZE(fsp2_cfg_patch_ff020008) },
	.fsp0_2d_cfg = { base_fsp0_2d_cfg, BASE_FSP0_2D_CFG_NUM, fsp0_2d_cfg_patch_ff020008, ARRAY_SIZE(fsp0_2d_cfg_patch_ff020008) },
	.ddrphy_pie = { base_ddrphy_pie, BASE_DDRPHY_PIE_NUM, NULL, 0 },
	.fsp_table = { 3000, 400, 100, 0 },
};

