/*
 * SPDX-License-Identifier:	GPL-2.0+
 *
 * AUTO-GENERATED by gen_ddr_tables.py -- DO NOT EDIT BY HAND.
 */


#include <linux/kernel.h>
#include <asm/arch/imx8m_ddr.h>
#include "ddr_patch.h"
#include "ddr_cfg_bases.h"

static const struct dram_cfg_patch ddrc_cfg_patch_01050008[] = {
	{ .pos = 5, .op = DRAM_PATCH_SET, .reg = 0x3d400064, .val = 0x5b0087 },
	{ .pos = 21, .op = DRAM_PATCH_SET, .reg = 0x3d400138, .val = 0x8d },
	{ .pos = 42, .op = DRAM_PATCH_SET, .reg = 0x3d400218, .val = 0xf070707 },
	{ .pos = 57, .op = DRAM_PATCH_SET, .reg = 0x3d402064, .val = 0xc0012 },
	{ .pos = 72, .op = DRAM_PATCH_SET, .reg = 0x3d402138, .val = 0x13 },
	{ .pos = 81, .op = DRAM_PATCH_SET, .reg = 0x3d403064, .val = 0x30005 },
	{ .pos = 96, .op = DRAM_PATCH_SET, .reg = 0x3d403138, .val = 0x5 },
};

const struct dram_profile_desc ucm_dram_profile_01050008 = {
	.ddrc_cfg = { base_ddrc_cfg, BASE_DDRC_CFG_NUM, ddrc_cfg_patch_01050008, ARRAY_SIZE(ddrc_cfg_patch_01050008) },
	.ddrphy_cfg = { base_ddrphy_cfg, BASE_DDRPHY_CFG_NUM, NULL, 0 },
	.fsp0_cfg = { base_fsp0_cfg, BASE_FSP0_CFG_NUM, NULL, 0 },
	.fsp1_cfg = { base_fsp1_cfg, BASE_FSP1_CFG_NUM, NULL, 0 },
	.fsp2_cfg = { base_fsp2_cfg, BASE_FSP2_CFG_NUM, NULL, 0 },
	.fsp0_2d_cfg = { base_fsp0_2d_cfg, BASE_FSP0_2D_CFG_NUM, NULL, 0 },
	.ddrphy_pie = { base_ddrphy_pie, BASE_DDRPHY_PIE_NUM, NULL, 0 },
	.fsp_table = { 3000, 400, 100, 0 },
};

