/*
 * SPDX-License-Identifier:	GPL-2.0+
 *
 * AUTO-GENERATED by gen_ddr_tables.py -- DO NOT EDIT BY HAND.
 */


#include <linux/kernel.h>
#include <asm/arch/imx8m_ddr.h>
#include "ddr_patch.h"
#include "ddr_cfg_bases.h"

static const struct dram_cfg_patch ddrc_cfg_patch_ff070010[] = {
	{ .pos = 18, .op = DRAM_PATCH_SET, .reg = 0x3d40011c, .val = 0x402 },
	{ .pos = 34, .op = DRAM_PATCH_SET, .reg = 0x3d4001c4, .val = 0x1 },
	{ .pos = 35, .op = DRAM_PATCH_SET, .reg = 0x3d4000f4, .val = 0x699 },
	{ .pos = 43, .op = DRAM_PATCH_INSERT, .reg = 0x3d40021c, .val = 0xf0f },
	{ .pos = 69, .op = DRAM_PATCH_SET, .reg = 0x3d40211c, .val = 0x302 },
	{ .pos = 78, .op = DRAM_PATCH_INSERT, .reg = 0x3d4020f4, .val = 0x599 },
	{ .pos = 93, .op = DRAM_PATCH_SET, .reg = 0x3d40311c, .val = 0x302 },
	{ .pos = 102, .op = DRAM_PATCH_INSERT, .reg = 0x3d4030f4, .val = 0x599 },
};

static const struct dram_cfg_patch ddrphy_cfg_patch_ff070010[] = {
	{ .pos = 82, .op = DRAM_PATCH_SET, .reg = 0x120056, .val = 0x3 },
	{ .pos = 83, .op = DRAM_PATCH_SET, .reg = 0x220056, .val = 0x3 },
};

static const struct dram_cfg_patch fsp0_cfg_patch_ff070010[] = {
	{ .pos = 8, .op = DRAM_PATCH_DELETE },
};

static const struct dram_cfg_patch fsp1_cfg_patch_ff070010[] = {
	{ .pos = 9, .op = DRAM_PATCH_DELETE },
};

static const struct dram_cfg_patch fsp2_cfg_patch_ff070010[] = {
	{ .pos = 9, .op = DRAM_PATCH_DELETE },
};

static const struct dram_cfg_patch ddrphy_pie_patch_ff070010[] = {
	{ .pos = 488, .op = DRAM_PATCH_SET, .reg = 0x2000b, .val = 0x34b },
	{ .pos = 492, .op = DRAM_PATCH_SET, .reg = 0x12000b, .val = 0x70 },
	{ .pos = 496, .op = DRAM_PATCH_SET, .reg = 0x22000b, .val = 0x1c },
};

const struct dram_profile_desc ucm_dram_profile_ff070010 = {
	.ddrc_cfg = { base_ddrc_cfg, BASE_DDRC_CFG_NUM, ddrc_cfg_patch_ff070010, ARRAY_SIZE(ddrc_cfg_patch_ff070010) },
	.ddrphy_cfg = { base_ddrphy_cfg, BASE_DDRPHY_CFG_NUM, ddrphy_cfg_patch_ff070010, ARRAY_SIZE(ddrphy_cfg_patch_ff070010) },
	.fsp0_cfg = { base_fsp0_cfg, BASE_FSP0_CFG_NUM, fsp0_cfg_patch_ff070010, ARRAY_SIZE(fsp0_cfg_patch_ff070010) },
	.fsp1_cfg = { base_fsp1_cfg, BASE_FSP1_CFG_NUM, fsp1_cfg_patch_ff070010, ARRAY_SIZE(fsp1_cfg_patch_ff070010) },
	.fsp2_cfg = { base_fsp2_cfg, BASE_FSP2_CFG_NUM, fsp2_cfg_patch_ff070010, ARRAY_SIZE(fsp2_cfg_patch_ff070010) },
	.fsp0_2d_cfg = { base_fsp0_2d_cfg, BASE_FSP0_2D_CFG_NUM, NULL, 0 },
	.ddrphy_pie = { base_ddrphy_pie, BASE_DDRPHY_PIE_NUM, ddrphy_pie_patch_ff070010, ARRAY_SIZE(ddrphy_pie_patch_ff070010) },
	.fsp_table = { 3000, 400, 100, 0 },
};

