/*
 * SPDX-License-Identifier:	GPL-2.0+
 *
 * AUTO-GENERATED by gen_ddr_tables.py -- DO NOT EDIT BY HAND.
 */


#include <linux/kernel.h>
#include <asm/arch/imx8m_ddr.h>
#include "ddr_patch.h"
#include "ddr_cfg_bases.h"

static const struct dram_cfg_patch ddrc_cfg_patch_05000010[] = {
	{ .pos = 4, .op = DRAM_PATCH_SET, .reg = 0x3d400024, .val = 0x2ee00 },
	{ .pos = 5, .op = DRAM_PATCH_SET, .reg = 0x3d400064, .val = 0x4900a8 },
	{ .pos = 6, .op = DRAM_PATCH_SET, .reg = 0x3d4000d0, .val = 0xc0030495 },
	{ .pos = 7, .op = DRAM_PATCH_SET, .reg = 0x3d4000d4, .val = 0x770000 },
	{ .pos = 8, .op = DRAM_PATCH_SET, .reg = 0x3d4000dc, .val = 0xc40024 },
	{ .pos = 12, .op = DRAM_PATCH_SET, .reg = 0x3d400100, .val = 0x1618141a },
	{ .pos = 13, .op = DRAM_PATCH_SET, .reg = 0x3d400104, .val = 0x504a6 },
	{ .pos = 14, .op = DRAM_PATCH_SET, .reg = 0x3d40010c, .val = 0x909000 },
	{ .pos = 15, .op = DRAM_PATCH_SET, .reg = 0x3d400110, .val = 0xb04060b },
	{ .pos = 16, .op = DRAM_PATCH_SET, .reg = 0x3d400114, .val = 0x2030909 },
	{ .pos = 17, .op = DRAM_PATCH_SET, .reg = 0x3d400118, .val = 0x1010006 },
	{ .pos = 18, .op = DRAM_PATCH_SET, .reg = 0x3d40011c, .val = 0x301 },
	{ .pos = 19, .op = DRAM_PATCH_SET, .reg = 0x3d400130, .val = 0x20500 },
	{ .pos = 20, .op = DRAM_PATCH_SET, .reg = 0x3d400134, .val = 0xb100002 },
	{ .pos = 21, .op = DRAM_PATCH_SET, .reg = 0x3d400138, .val = 0xad },
	{ .pos = 22, .op = DRAM_PATCH_SET, .reg = 0x3d400144, .val = 0x78003c },
	{ .pos = 23, .op = DRAM_PATCH_SET, .reg = 0x3d400180, .val = 0x2580012 },
	{ .pos = 24, .op = DRAM_PATCH_SET, .reg = 0x3d400184, .val = 0x1e0493e },
	{ .pos = 26, .op = DRAM_PATCH_SET, .reg = 0x3d400190, .val = 0x4938208 },
	{ .pos = 28, .op = DRAM_PATCH_SET, .reg = 0x3d4001b4, .val = 0x1308 },
	{ .pos = 36, .op = DRAM_PATCH_SET, .reg = 0x3d400108, .val = 0x60c1514 },
};

static const struct dram_cfg_patch ddrphy_cfg_patch_05000010[] = {
	{ .pos = 66, .op = DRAM_PATCH_SET, .reg = 0x200c5, .val = 0xa },
	{ .pos = 81, .op = DRAM_PATCH_SET, .reg = 0x20056, .val = 0x2 },
	{ .pos = 145, .op = DRAM_PATCH_SET, .reg = 0x20008, .val = 0x258 },
};

static const struct dram_cfg_patch fsp0_cfg_patch_05000010[] = {
	{ .pos = 1, .op = DRAM_PATCH_SET, .reg = 0x54003, .val = 0x960 },
	{ .pos = 10, .op = DRAM_PATCH_SET, .reg = 0x54019, .val = 0x24c4 },
	{ .pos = 15, .op = DRAM_PATCH_SET, .reg = 0x5401f, .val = 0x24c4 },
	{ .pos = 22, .op = DRAM_PATCH_SET, .reg = 0x54032, .val = 0xc400 },
	{ .pos = 23, .op = DRAM_PATCH_SET, .reg = 0x54033, .val = 0x3124 },
	{ .pos = 28, .op = DRAM_PATCH_SET, .reg = 0x54038, .val = 0xc400 },
	{ .pos = 29, .op = DRAM_PATCH_SET, .reg = 0x54039, .val = 0x3124 },
};

static const struct dram_cfg_patch fsp0_2d_cfg_patch_05000010[] = {
	{ .pos = 1, .op = DRAM_PATCH_SET, .reg = 0x54003, .val = 0x960 },
	{ .pos = 11, .op = DRAM_PATCH_SET, .reg = 0x54019, .val = 0x24c4 },
	{ .pos = 16, .op = DRAM_PATCH_SET, .reg = 0x5401f, .val = 0x24c4 },
	{ .pos = 23, .op = DRAM_PATCH_SET, .reg = 0x54032, .val = 0xc400 },
	{ .pos = 24, .op = DRAM_PATCH_SET, .reg = 0x54033, .val = 0x3124 },
	{ .pos = 29, .op = DRAM_PATCH_SET, .reg = 0x54038, .val = 0xc400 },
	{ .pos = 30, .op = DRAM_PATCH_SET, .reg = 0x54039, .val = 0x3124 },
};

static const struct dram_cfg_patch ddrphy_pie_patch_05000010[] = {
	{ .pos = 488, .op = DRAM_PATCH_SET, .reg = 0x2000b, .val = 0x4b },
	{ .pos = 489, .op = DRAM_PATCH_SET, .reg = 0x2000c, .val = 0x96 },
	{ .pos = 490, .op = DRAM_PATCH_SET, .reg = 0x2000d, .val = 0x5dc },
};

const struct dram_profile_desc ucm_dram_profile_05000010 = {
	.ddrc_cfg = { base_ddrc_cfg, BASE_DDRC_CFG_NUM, ddrc_cfg_patch_05000010, ARRAY_SIZE(ddrc_cfg_patch_05000010) },
	.ddrphy_cfg = { base_ddrphy_cfg, BASE_DDRPHY_CFG_NUM, ddrphy_cfg_patch_05000010, ARRAY_SIZE(ddrphy_cfg_patch_05000010) },
	.fsp0_cfg = { base_fsp0_cfg, BASE_FSP0_CFG_NUM, fsp0_cfg_patch_05000010, ARRAY_SIZE(fsp0_cfg_patch_05000010) },
	.fsp1_cfg = { base_fsp1_cfg, BASE_FSP1_CFG_NUM, NULL, 0 },
	.fsp2_cfg = { base_fsp2_cfg, BASE_FSP2_CFG_NUM, NULL, 0 },
	.fsp0_2d_cfg = { base_fsp0_2d_cfg, BASE_FSP0_2D_CFG_NUM, fsp0_2d_cfg_patch_05000010, ARRAY_SIZE(fsp0_2d_cfg_patch_05000010) },
	.ddrphy_pie = { base_ddrphy_pie, BASE_DDRPHY_PIE_NUM, ddrphy_pie_patch_05000010, ARRAY_SIZE(ddrphy_pie_patch_05000010) },
	.fsp_table = { 2400, 400, 100, 0 },
};

