--- board/compulab/plat/imx8mm/ddr/Makefile
+++ board/compulab/plat/imx8mm/ddr/Makefile
@@ -1,5 +1,5 @@
 obj-y += ddr.o
-obj-y += lpddr4_timing_13.o
+obj-y += lpddr4_timing_13-2.o
 obj-y += lpddr4_timing_ff.o
 obj-y += lpddr4_timing_01.o
 ifndef CONFIG_TARGET_MCM_IMX8M_MINI
