obj-y += ddr.o
obj-y += ddr_patch.o
obj-y += ddr_cfg_bases.o
obj-y += lpddr4_timing_01050008.o
obj-y += lpddr4_timing_01061010.o
ifndef CONFIG_TARGET_MCM_IMX8M_MINI
obj-y += lpddr4_timing_05000010.o
endif
obj-y += lpddr4_timing_1b000008.o
obj-y += lpddr4_timing_ff000110.o
obj-y += lpddr4_timing_ff020008.o
obj-y += lpddr4_timing_ff070010.o
obj-y += lpddr4_timing_ff070018.o
obj-y += lpddr4_timing_ff070110.o
