obj-$(CONFIG_VIDEO_IMX8MP_HDMI) += dw_hdmi-imx.o dw-hdmi-detect.o
obj-$(CONFIG_IMX8MP_HDMI_PAVI) += imx8mp-hdmi-pavi.o
obj-$(CONFIG_VIDEO_DW_HDMI_I2C) += dw-hdmi-i2c.o
obj-$(CONFIG_VIDEO_DW_HDMI) += dw-hdmi.o
