ifdef CONFIG_TARGET_UCM_IMX8M_PLUS
obj-y += lpddr4_timing.o
else
obj-y += ddr.o
obj-y += lpddr4_timing_ff020008.o
obj-y += lpddr4_timing_ff000110.o
obj-y += lpddr4_timing_01061010.o
obj-y += lpddr4_timing_01050008.o
endif
